services:
  yolosint:
    image: savant42/yolosint:latest
    ports:
      - "8042:8080"
    environment:
      - PORT=8080
      - CACHE_DIR=/cache
    volumes:
      - /volume1/docker/yolosint/cache:/cache
    restart: unless-stopped
