services:
  yolosint:
    build: .
    image: savant42/yolosint:latest
    ports:
      - "8042:8080"
    environment:
      - PORT=8080
      - CACHE_DIR=/cache
    volumes:
      - ./cache:/cache
    restart: unless-stopped
